{"uuid": "01b56fbd-2973-4f09-81cf-83d5f0014dcb", "children": ["cfaa2198-c64f-4abf-80d8-56945a0dcb43", "eabd764e-f1e7-4896-bca2-0c0aafebb11b", "860b5ba4-7159-4c51-ac18-816415a94a22", "1a4bf018-1fcc-4a5b-954d-b05725e45c02", "198ae3f8-21a8-4bed-9fce-f65b2885bd12", "4e4880f6-82db-4be5-94c5-e8fe99f06297", "15396210-7b72-4454-ac3d-ba8bcfcaa83e"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nThe chromedriver version cannot be discovered\n\n", "trace": "  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.get_web_driver(\"chrome\")\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\base\\DriverClass.py\", line 8, in get_web_driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 82, in __init__\n    service.path = DriverFinder.get_path(service, options)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 43, in get_path\n    raise err\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 40, in get_path\n    path = shutil.which(service.path) or SeleniumManager().driver_location(options)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 101, in driver_location\n    result = self.run(args)\n             ^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 122, in run\n    raise SeleniumManagerException(f\"Selenium Manager failed for: {command}.\\n{result}{stderr}\")\n"}, "start": 1708509129922, "stop": 1708509135767}], "start": 1708509129922, "stop": 1708509136507}