{"uuid": "02955318-716a-44d4-8ba6-5e1fe7fd9bdc", "children": ["31bc9354-8b4a-4e30-95fe-16d82796f3e3", "78adc92a-954f-4429-aae7-123848fef61e", "1c63091d-4697-456b-affb-cd89f155c4f3", "f7ae53d0-5c1c-4844-8077-8d380ec7b113", "f4e9b286-ebe2-4906-93ee-7d47a015977d", "b446cbff-e3dd-4232-974e-2dc2d477e6d5", "6b8debc9-70de-4f11-9a38-fd82cf776238"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nThe chromedriver version cannot be discovered\n\n", "trace": "  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.get_web_driver(\"chrome\")\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\base\\DriverClass.py\", line 8, in get_web_driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 82, in __init__\n    service.path = DriverFinder.get_path(service, options)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 43, in get_path\n    raise err\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 40, in get_path\n    path = shutil.which(service.path) or SeleniumManager().driver_location(options)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 101, in driver_location\n    result = self.run(args)\n             ^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 122, in run\n    raise SeleniumManagerException(f\"Selenium Manager failed for: {command}.\\n{result}{stderr}\")\n"}, "start": 1708586657593, "stop": 1708586662579}], "start": 1708586657593, "stop": 1708586663220}