{"uuid": "4e1bdddb-18d1-4fc4-80cd-cca2e3f0f1a8", "children": ["f3d46412-e810-4c00-a5ff-eec4115c1ac4", "c1655901-e04f-43e8-94ac-7a40cdab110c"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nThe chromedriver version cannot be discovered\n\n", "trace": "  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.get_web_driver(\"chrome\")\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\base\\DriverClass.py\", line 8, in get_web_driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 82, in __init__\n    service.path = DriverFinder.get_path(service, options)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 43, in get_path\n    raise err\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 40, in get_path\n    path = shutil.which(service.path) or SeleniumManager().driver_location(options)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 101, in driver_location\n    result = self.run(args)\n             ^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 122, in run\n    raise SeleniumManagerException(f\"Selenium Manager failed for: {command}.\\n{result}{stderr}\")\n"}, "start": 1708590378663, "stop": 1708590383846}], "start": 1708590378663, "stop": 1708590384056}