{"uuid": "4dceb6f8-4883-4561-a934-4ee9f07ea98e", "children": ["0675adde-49ee-4cf7-a8ec-deec92fb8c6d", "6761f5ec-0684-4f85-8497-2c4ba57ba99d", "c07c746c-460b-4162-a847-e67ebe9a6fa2", "df1c3c94-41c4-419f-baca-15666c310a79", "81875173-cefb-4b0e-9b81-3cb625e82c8d", "a1b32b09-092f-4eb0-b81a-fbf4bde51380"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nThe chromedriver version cannot be discovered\n\n", "trace": "  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.get_web_driver(\"chrome\")\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\base\\DriverClass.py\", line 8, in get_web_driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 82, in __init__\n    service.path = DriverFinder.get_path(service, options)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 43, in get_path\n    raise err\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 40, in get_path\n    path = shutil.which(service.path) or SeleniumManager().driver_location(options)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 101, in driver_location\n    result = self.run(args)\n             ^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 122, in run\n    raise SeleniumManagerException(f\"Selenium Manager failed for: {command}.\\n{result}{stderr}\")\n"}, "start": 1708590360351, "stop": 1708590364801}], "start": 1708590360351, "stop": 1708590365396}