{"uuid": "b67e9d6d-6e07-4d4a-ad64-c915b36f538e", "children": ["5aa70742-f99e-4172-b20d-eca615141c9f", "b9dc7837-b7c2-4547-8c2d-b1c8277b1553", "a7b539d1-31f3-4f69-bffa-51b822b8beb5", "a65264c1-4240-4181-ae48-c3321a1dccf4", "f95d19e3-690b-4526-8a54-f25229ecfc27", "28acf5b8-d37d-4dc1-b19a-465ecbf60195"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nThe chromedriver version cannot be discovered\n\n", "trace": "  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.get_web_driver(\"chrome\")\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\PycharmProjects\\seleniumproj\\SeleniumFrameWork\\base\\DriverClass.py\", line 8, in get_web_driver\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 82, in __init__\n    service.path = DriverFinder.get_path(service, options)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 43, in get_path\n    raise err\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 40, in get_path\n    path = shutil.which(service.path) or SeleniumManager().driver_location(options)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 101, in driver_location\n    result = self.run(args)\n             ^^^^^^^^^^^^^^\n  File \"C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py\", line 122, in run\n    raise SeleniumManagerException(f\"Selenium Manager failed for: {command}.\\n{result}{stderr}\")\n"}, "start": 1708509124498, "stop": 1708509128984}], "start": 1708509124498, "stop": 1708509129867}